name: Build and Release OnePlus Kernels with KernelSU Next & SUSFS

permissions:
  contents: write  # 允许写入存储库内容（用于推送 tag）
  actions: write   # 允许触发 actions

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: true

jobs:
  build-kernel-10T:
    uses: ./.github/workflows/Build-ksunext-10T-SUSFS.yml
    secrets: inherit
  build-kernel-11:
    uses: ./.github/workflows/Build-ksunext-11-SUSFS.yml
    secrets: inherit
  build-kernel-12:
    uses: ./.github/workflows/Build-ksunext-12-SUSFS.yml
    secrets: inherit
  build-kernel-12r:
    uses: ./.github/workflows/Build-ksunext-12r-SUSFS.yml
    secrets: inherit
  build-kernel-Ace2:
    uses: ./.github/workflows/Build-ksunext-Ace2-SUSFS.yml
    secrets: inherit
  build-kernel-Ace2Pro:
    uses: ./.github/workflows/Build-ksunext-Ace2Pro-SUSFS.yml
    secrets: inherit
  build-kernel-Ace3Pro:
    uses: ./.github/workflows/Build-ksunext-Ace3Pro-SUSFS.yml
    secrets: inherit
  build-kernel-Ace3V:
    uses: ./.github/workflows/Build-ksunext-Ace3V-SUSFS.yml
    secrets: inherit
  build-kernel-Ace5:
    uses: ./.github/workflows/Build-ksunext-Ace5-SUSFS.yml
    secrets: inherit
  build-kernel-PadPro:
    uses: ./.github/workflows/Build-ksunext-PadPro-SUSFS.yml
    secrets: inherit
  build-kernel-AcePro:
    uses: ./.github/workflows/Build-ksunext-AcePro-SUSFS.yml
    secrets: inherit

  trigger-release:
    runs-on: ubuntu-latest
    needs:
      - build-kernel-10T
      - build-kernel-11
      - build-kernel-12
      - build-kernel-12r
      - build-kernel-Ace2
      - build-kernel-Ace2Pro
      - build-kernel-Ace3Pro
      - build-kernel-Ace3V
      - build-kernel-Ace5
      - build-kernel-PadPro
      - build-kernel-AcePro
    if: ${{ inputs.make_release }}
    env:
      REPO_OWNER: TheWildJames
      REPO_NAME: OnePlus_KernelSU_SUSFS
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "*TEST BUILD* OnePlus Kernels With KernelSU Next & SUSFS v1.5.5-CI *TEST BUILD*"
      RELEASE_NOTES: |
        This release contains KernelSU Next and SUSFS v1.5.5-CI
        
        Features:
        [+] KernelSU-Next
        [+] SUSFS CI
        [+] VFS HOOK
        [+] Magic Mount Support

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate and Create New Tag
        run: |
            LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name' || echo "")
            if [[ -z "$LATEST_TAG" ]]; then
              LATEST_TAG="v1.5.5-r0"
            fi
            
            NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2+1; printf "%s-r%d", $1, suffix}')
            echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
            
            git tag $NEW_TAG
            git push origin $NEW_TAG
            
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: true
          release_name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets Dynamically
        run: |
          for file in ./downloaded-artifacts/kernel-*/*; do
              if [ -d "$file" ]; then
                  continue
              fi
              echo "Uploading $file..."
              gh release upload ${{ env.NEW_TAG }} "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ env.NEW_TAG }}

      - name: Display Files Uploaded
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*